# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oL1y-mlXiLzm4ZFrFZgQWsYUBnMqgdTr
"""

import numpy as np
number = 1
for i in range(number):
  m = np.random.randint(1, 16)
  n = np.random.randint(1, 16)
  k = np.random.randint(1, 16)
  A = np.random.normal(size = m * n).reshape([m , n])
  B = np.random.normal(size = n * k).reshape([n, k])
  result = np.dot(A, B)
  print(result)